
# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - pennywise-free

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install server dependencies
        run: |
          cd server
          npm install

      - name: Move server package.json to root
        run: |
          mv server/package.json .

      - name: Install client dependencies and build
        run: |
          cd client
          npm install
          npm run build

      - name: Prepare artifact for deployment
        run: |
          cd client
          find . -mindepth 1 -maxdepth 1 ! -name 'build' -exec rm -rf {} +
          cd ..
          zip release.zip ./* -r

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_958B2D00396143A0BA1E61E234ED9C10 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1A2AD3EA91DF4E3E867133C723EB8192 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9C11875D27534CF08F828DBC5719780C }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'pennywise-free'
          slot-name: 'Production'
          package: .
          